algoritmo "Ex-Qual-idade-Aula-06"

  var
     ano_nascimento, ano_atual, resultado: inteiro

  inicio

        escreva("Em que ano você nasceu? ")
        leia(ano_nascimento)
        
        escreva("Em que ano estamos? ")
        leia(ano_atual)
        
        resultado <- ano_atual - ano_nascimento
        
        escreva("Você tem ", resultado, " anos!")
        
        

fimalgoritmo