algoritmo "Enquanto-while-p3-Aula-09"

  var

      num1, user, salto: inteiro

  inicio

        num1 <- 0
        
        escreval("Digite um valor: ")
        leia(user)
        
        escreval("Qual valor do salto? ")
        leia(salto)
        
        enquanto num1 <= user faca
        
        escreval(num1)
        
        num1 <- num1 + salto
        
        fimenquanto

fimalgoritmo